### ISSUE TITLE
Portfolio: Animations and Transitions Review.

### ISSUE THREAD

**Issue by maximoortelli** [maximoortelli/Portfolio-setup-and-mobile--first#10]
_Portfolio: Animations and transitions version is an exercise where I will add animations and transitions to my portfolio.The goal here is to master all of the tools and best practices learned about in previous steps to use them in all Microverse projects and most likely in my future job as well._

**Comment by IsraArvin** [comment]
Hey there, I've reviewed your code, and it's looking great! 🎉 You've done an excellent job with the styles, and the hover effects and transitions add a nice touch. Awesome work! 👏

**Comment by jrraul4** [comment]
Hi Maximo great work, My review would be that you should write all the code in English so it is understandable for most people who could use it as a guide or want to correct it.
